# Generated by Django 4.2.2 on 2023-07-07 15:09

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='وضعیت کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='کاربر ویژه تا'),
        ),
    ]
