# Generated by Django 4.2.2 on 2023-06-26 13:41

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(default='', help_text='آدرس slug', max_length=255, unique=True, verbose_name='نامک')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'انتشار'), ('D', 'پیش نویس')], max_length=1, verbose_name='وضعیت')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها ',
            },
        ),
    ]
