# Generated by Django 4.2.2 on 2023-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.ManyToManyField(to='blog.category', verbose_name='دسته بندی ها '),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=1, verbose_name='پوزیشن'),
        ),
    ]
