# Generated by Django 4.2.2 on 2023-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_settings_alter_category_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'عنوان سایت', 'verbose_name_plural': 'عنوان سایت'},
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ManyToManyField(related_name='members', to='blog.category', verbose_name='دسته بندی ها '),
        ),
    ]
