# Generated by Django 4.2.2 on 2023-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_member_is_special_alter_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی ')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blog.ipaddress', verbose_name='بازدید ها '),
        ),
    ]
