# Generated by Django 4.2.2 on 2023-07-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_ipaddress_member_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='hits',
        ),
    ]
