# Generated by Django 4.2.2 on 2023-07-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_articlehit_member_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته بندی ها'),
        ),
    ]
