# Generated by Django 4.2.2 on 2023-07-22 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('blog', '0016_member_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ratings',
        ),
        migrations.AddField(
            model_name='member',
            name='ratings',
            field=models.ManyToManyField(to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
