# Generated by Django 4.2.2 on 2023-07-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_member_ratings_member_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ratings',
        ),
    ]
