# Generated by Django 4.2.2 on 2023-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_member_ratings_date_myrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrating',
            name='foo',
            field=models.TextField(null=True),
        ),
    ]
