# Generated by Django 4.2.2 on 2023-07-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_myrating_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrating',
            name='foo',
        ),
    ]
