# Generated by Django 4.2.2 on 2023-07-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0004_alter_rating_id_alter_userrating_id'),
        ('blog', '0022_remove_myrating_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrating',
            name='published',
            field=models.ManyToManyField(null=True, related_name='pub', to='star_ratings.userrating'),
        ),
    ]
