# Generated by Django 4.2.2 on 2023-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_myrating_published_myrating_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='object_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
