# Generated by Django 4.2.2 on 2023-07-23 13:49

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_myrating_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrating',
            name='published',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myrating',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
