# Generated by Django 4.2.2 on 2023-07-30 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0027_myrating_published_alter_myrating_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_author': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
